import { sva } from "@styled-system/css"

export const recipe = sva({
  slots: [
    "root",
    "content",
    "section",
    "sectionTitle",
    "navItems",
    "navItem",
    "label",
    "overlay",
    "toggle",
  ],
  base: {
    root: {
      display: "block",
      position: "sticky",
      top: "3.5",
      width: "full",
      left: 0,
      zIndex: 40,
      height: "100vh",
      borderRight: "base",
      overflow: "hidden",
      mdDown: {
        display: "none",
      },
    },
    content: {
      height: "100%",
      px: 4,
      py: 6,
      overflowY: "auto",
    },
    section: {
      display: "flex",
      flexDirection: "column",
      gap: 1,
      mb: 6,
    },
    sectionTitle: {
      rounded: "md",
      px: 2,
      py: 1,
      fontSize: "sm",
      fontWeight: "medium",
      color: "foreground",
    },
    navItems: {
      display: "grid",
      gridAutoFlow: "row",
      gridAutoRows: "max-content",
      gap: 0.5,
      fontSize: "sm",
    },
    navItem: {
      position: "relative",
      display: "flex",
      height: 8,
      width: "100%",
      alignItems: "center",
      rounded: "lg",
      px: 2,
      fontWeight: "normal",
      color: "foreground",
      textDecoration: "none",
      transition: "colors",
      transitionDuration: "fastest",
      _hover: {
        bg: "accent/90",
        color: "accent.foreground",
      },
      _after: {
        content: '""',
        position: "absolute",
        insetX: 0,
        insetY: "-2px",
        rounded: "lg",
      },
    },
    label: {
      ml: 2,
      rounded: "md",
      px: 1.5,
      py: 0.5,
      fontSize: "xs",
      lineHeight: "none",
      textDecoration: "none",
      _groupHover: {
        textDecoration: "none",
      },
    },
    overlay: {
      position: "fixed",
      inset: 0,
      zIndex: 30,
      bg: "muted/50",
    },
    toggle: {
      position: "fixed",
      top: 4,
      right: 4,
      zIndex: 50,
      p: 2,
      bg: "background",
      border: "base",
      rounded: "md",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      transition: "colors",
      transitionDuration: "fast",
      _hover: {
        bg: "accent",
        color: "accent.foreground",
        opacity: 0.9,
      },
    },
  },
  variants: {
    active: {
      true: {
        navItem: {
          bg: "primary/10",
          color: "primary",
          fontWeight: "medium",
          _hover: {
            bg: "primary/20",
            color: "primary",
          },
        },
      },
    },
  },
})
