export const styleTokenReferenceMap = {
  color: ["backgroundColor", "borderBottomColor", "borderColor", "color"],
  spacing: [
    "bottom",
    "gap",
    "height",
    "inset",
    "left",
    "margin",
    "marginBlock",
    "marginBottom",
    "marginInline",
    "marginLeft",
    "marginRight",
    "marginTop",
    "maxHeight",
    "maxWidth",
    "minHeight",
    "minWidth",
    "padding",
    "paddingBlock",
    "paddingBottom",
    "paddingInline",
    "paddingLeft",
    "paddingRight",
    "paddingTop",
    "right",
    "top",
    "width",
  ],
  radius: ["borderRadius"],
  shadow: ["boxShadow"],
  motion: {
    duration: ["animationDuration", "transitionDuration"],
    easing: ["animationTimingFunction", "transitionTimingFunction"],
  },
  fontSize: ["fontSize"],
} as const
