import { defineSlotRecipe } from "../define.ts"

export const selectRecipe = defineSlotRecipe({
  name: "select",
  slots: [
    "root",
    "group",
    "value",
    "trigger",
    "viewport",
    "content",
    "label",
    "item",
    "itemIndicator",
    "separator",
  ],
  base: {
    root: {},
    group: {},
    value: {
      color: "color.fg.default",
      textStyle: "typography.label.md",
    },
    trigger: {
      display: "flex",
      width: "100%",
      minHeight: "2.5rem",
      paddingInline: "spacing.3",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "spacing.2",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "color.stroke.default",
      borderRadius: "radius.md",
      backgroundColor: "color.bg.surface",
      color: "color.fg.default",
      textStyle: "typography.label.md",
      cursor: "pointer",
      transitionProperty: "background-color, border-color, color, box-shadow",
      transitionDuration: "motion.duration.fast",
      transitionTimingFunction: "motion.easing.standard",
      "&[data-placeholder]": {
        color: "color.fg.subtle",
      },
      "&:focus-visible": {
        outline: "2px solid var(--jds-color-focus-ring)",
        outlineOffset: "2px",
      },
      _disabled: {
        cursor: "not-allowed",
        opacity: 0.5,
      },
    },
    viewport: {
      "&[data-position='popper']": {
        width: "100%",
        minWidth: "var(--radix-select-trigger-width)",
        height: "var(--radix-select-trigger-height)",
      },
    },
    content: {
      position: "relative",
      zIndex: "100",
      minWidth: "100%",
      maxHeight: "24rem",
      overflow: "hidden",
      paddingBlock: "spacing.1",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "color.stroke.subtle",
      borderRadius: "radius.md",
      backgroundColor: "color.bg.elevated",
      color: "color.fg.default",
      boxShadow: "shadow.lg",
      "&[data-state='open']": {
        animationName: "fade-in",
        animationDuration: "motion.duration.normal",
      },
      "&[data-position='popper'][data-side='top']": {
        transform: "translateY(-0.25rem)",
      },
      "&[data-position='popper'][data-side='bottom']": {
        transform: "translateY(0.25rem)",
      },
      "&[data-position='popper'][data-side='left']": {
        transform: "translateX(-0.25rem)",
      },
      "&[data-position='popper'][data-side='right']": {
        transform: "translateX(0.25rem)",
      },
    },
    label: {
      paddingTop: "spacing.2",
      paddingBottom: "spacing.1",
      paddingLeft: "spacing.8",
      paddingRight: "spacing.2",
      color: "color.fg.muted",
      textStyle: "typography.label.sm",
    },
    item: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      minHeight: "2.25rem",
      paddingLeft: "spacing.8",
      paddingRight: "spacing.2",
      borderRadius: "radius.sm",
      color: "color.fg.default",
      cursor: "default",
      userSelect: "none",
      textStyle: "typography.body.md",
      "&:focus-visible, &[data-highlighted]": {
        outline: "none",
        backgroundColor: "color.bg.subtle",
      },
      "&[data-disabled]": {
        pointerEvents: "none",
        opacity: 0.5,
      },
    },
    itemIndicator: {
      position: "absolute",
      left: "spacing.2",
      display: "flex",
      width: "1rem",
      height: "1rem",
      alignItems: "center",
      justifyContent: "center",
      color: "color.icon.accent",
    },
    separator: {
      marginBlock: "spacing.1",
      marginInline: "spacing.1",
      height: "1px",
      backgroundColor: "color.stroke.subtle",
    },
  },
  variants: {},
  compoundVariants: [],
  defaultVariants: {},
})
