name: Build & Deploy Docs
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - dev
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: ./.github/actions/setup

      - name: build
        run: pnpm turbo build

      - name: Upload Storybook artifact for Chromatic
        uses: actions/upload-artifact@v4
        with:
          name: ui-artifact
          path: packages/ui/storybook-static

      - name: Upload Docs artifact for AWS
        uses: actions/upload-artifact@v4
        with:
          name: docs-artifact
          path: app/docs/out

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: ./.github/actions/setup

      - name: Download  Docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-artifact
          path: app/docs/out

      - name: deploy docs to vercel
        uses: ./.github/actions/vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: --prod
          workingDir: app/docs

      - name: cache playwright
        uses: ./.github/actions/playwright
