name: Build & Deploy Docs
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - dev
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: ./.github/actions/setup

      - name: build
        run: pnpm turbo build

      - name: Get changed files - ui
        id: changed-ui-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            package/ui/**

      - name: deploy storybook using chromatic
        uses: ./.github/actions/chromatic
        if: ${{steps.changed-ui-files.outputs.all_changed_and_modified_files_count != '0'}}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/ui
          storybookBuildDir: storybook-static

      - name: Get changed files - docs
        id: changed-docs-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            app/docs/**

      - name: deploy docs to AWS S3 + Cloudfront
        uses: ./.github/actions/deploy
        if: ${{steps.changed-docs-files.outputs.all_changed_and_modified_files_count != '0'}}
        with:
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket_name: ${{ secrets.AWS_S3_BUCKET_NAME }}
          aws_cloudfront_id: ${{ secrets.AWS_CLOUDFRONT_ID }}
