# design 브랜치의 tokens.json 파일에 대한 push 감지
on:
  push:
    branches:
      - token
    paths:
      - "tokens.json"

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.4.0

      # 디자인 파일 변환 후 생성된 파일도 push해서 main 브랜치로 병합하는 PR을 생성
      - name: install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Token Transformer
        run: |
          node transformToken.js
          git config --global user.name "whdgur5717"
          git config --global user.email "whdgur5717@gmail.com"
          git add .
          git commit -m '피그마 디자인 파일 변환'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN}}
      - name: Create Pull Request
        run: gh pr create -B main -H token --title '💄 디자인 토큰 업데이트' --body '디자인 토큰이 업데이트 후 변환작업을 수행했습니다.'
        env:
          GITHUB_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
